### ISSUE TITLE
System.InvalidCastException  while comparing dynamic objects

### ISSUE THREAD

**Issue by kirillkovalenko** [GregFinzer/Compare-Net-Objects#103]
After upgrading CompareNETObjects package some dynamic object related tests stopped to working.

Exception:
```
Message: System.InvalidCastException : Unable to cast object of type 'S.S.Data.Delta`1[S.S.Core.Tests.Data.DeltaNestedTests+First]' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.
```

Callstack:
```
at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.HandleDynamicObject(Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.GetCurrentProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)
```

Some previous version did work, but cannot say for sure what version was that.

The objects being compared are equal from what I can tell.

**Comment by GregFinzer** [comment]
Is this .net core? Can you post example code?

**Comment by GregFinzer** [comment]
There are already passing dynamic tests in solution.   You may want to try extending the tests.

**Comment by kirillkovalenko** [comment]
Below is an isolated example that reproduces the issue. 

[Compare103.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/2108016/Compare103.zip)

```c#
using KellermanSoftware.CompareNetObjects;
using System;
using System.Web.Http.OData;
using Xunit;

public class Entity
{
    public Guid Id { get; set; }

    public String Name { get; set; }
}

public class Issue103
{
    [Fact]
    public void Manifests()
    {
        Delta<Entity> x = new Delta<Entity>();

        dynamic dynamicX = x;
        dynamicX.Name = nameof(Entity);
        dynamicX.Id = typeof(Entity).GUID;

        Delta<Entity> y = new Delta<Entity>();

        dynamic dynamicY = y;
        dynamicY.Name = nameof(Entity);
        dynamicY.Id = typeof(Entity).GUID;

        CompareLogic comparer = new CompareLogic();
        ComparisonResult result = comparer.Compare(y, x);

        Assert.True(result.AreEqual);
    }
}
```

Call stack:
```none
Test Name:	Compare103.Issue103.Manifests
Test FullName:	Compare103.Issue103.Manifests
Test Source:	C:\Users\kiril\source\repos\Compare103\Compare103\Issue103.cs : line 19
Test Outcome:	Failed
Test Duration:	0:00:00.5

Result:
at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.HandleDynamicObject(Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.GetCurrentProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)
   at Compare103.Issue103.Manifests() in C:\Users\kiril\source\repos\Compare103\Compare103\Issue103.cs:line 34
Result Message:	System.InvalidCastException : Unable to cast object of type 'System.Web.Http.OData.Delta`1[Compare103.Entity]' to type 'System.Collections.Generic.IDictionary`2[System.String,System.Object]'.

```

**Comment by GregFinzer** [comment]
Thanks.  It will be a while until I look at this.

**Comment by GregFinzer** [comment]
Waiting for an answer from these questions:

https://stackoverflow.com/questions/51120050/how-do-i-get-the-properties-and-fields-of-a-dynamic-object

https://stackoverflow.com/questions/51120031/how-do-i-detect-an-expandoobject-vs-a-dynamic-object

https://social.msdn.microsoft.com/Forums/vstudio/en-US/1bd3190b-34f7-4072-bc60-551ecec127dc/getting-dynamic-properties?forum=csharpgeneral

**Comment by GregFinzer** [comment]
@kirillkovalenko After some research I determined that dynamic objects where never compared for you.  Compare .NET Objects currently supports Expando Objects but does not support Dynamic Objects.  I was thinking about supporting it but TryGetMember requires Microsoft.CSharp which requires the .NET Framework 4.5 and higher.  It would also require some complex binder caching since a compiler is actually spun up for each variable call.  Support for .NET Framework 4.0 ends in 2020.  I will upgrade Compare .NET Objects to version 4.5 then and implement this.  

https://stackoverflow.com/questions/5306018/how-to-call-dynamicobject-trygetmember-directly

**_"C# has to actually instantiate a compiler to figure out how to execute the member/method."_**

**Comment by GregFinzer** [comment]
FYI, I changed the exception to a NotSupported exception that points to this issue.

**Comment by callmenoob** [comment]
im having the same issue

**Comment by GregFinzer** [comment]
@callmenoob As mentioned above, this feature will be implemented in 2020.

**Comment by GregFinzer** [comment]
Just to give everyone an update that is hoping to get this feature.  This is a major change.  I am swamped with overtime on my day job and the normal weeknight and weekend hours for my side business Kellerman Software.

**Comment by GregFinzer** [comment]
Implemented.
