### ISSUE TITLE
Cannot ignore ref struct properties

### ISSUE THREAD

**Issue by ltrzesniewski** [GregFinzer/Compare-Net-Objects#161]
CompareNETObjects fails when it encounters an object which contains a `ref struct` property, which is expected since you can't access those through reflection.

Unfortunately, you can't ignore such a property either, as the library tries to read the property *before* it filters out ignored members. Filtering out properties before trying to read them should fix this issue.

Sample repro:

```C#
internal class Program
{
    public RefStruct Item => default;

    public static void Main()
    {
        var compareLogic = new CompareLogic(new ComparisonConfig
        {
            MembersToIgnore =
            {
                nameof(Item)
            }
        });

        compareLogic.Compare(new Program(), new Program());
    }
}

public ref struct RefStruct
{
}
```

Output:

```
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.AddPropertyInfos(Object objectValue, Type objectType, IEnumerable`1 properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at ConsoleApp.Program.Main() in C:\Dev\TempProjects\ConsoleApp\ConsoleApp\Program.cs:line 19
```

**Comment by GregFinzer** [comment]
Thank you for reporting this issue.

**Comment by goyzhang** [comment]
@ltrzesniewski  what version are you running with? I got no issue running your code.

**Comment by ltrzesniewski** [comment]
I tested it with the latest version: 1.49.0.

Note that this code will probably not crash if you test it with an old runtime which doesn't understand `IsByRefLikeAttribute`.

Here's the full project which reproduces the issue, I just added some console output: 
[ConsoleApp.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/3313580/ConsoleApp.zip)

**Comment by GregFinzer** [comment]
@ltrzesniewski I have created a fix, ignoring the issue.

**Comment by ltrzesniewski** [comment]
Thanks!
