### ISSUE TITLE
exception comparing two string arrays

### ISSUE THREAD

**Issue by timrobinson33** [GregFinzer/Compare-Net-Objects#199]
Trying to compare two string arrays ignoring collection order when the second one starts with a null value.
```
var compareLogic = new CompareLogic();
compareLogic.Config.IgnoreCollectionOrder = true;
ComparisonResult result = compareLogic.Compare(new[] {"a", "b"}, new[] {null, "a"});
```
throws 
```
Unhandled exception. System.Exception: Invalid CollectionMatchingSpec.  No such property (null) for type String 
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
```

**Comment by GregFinzer** [comment]
@timrobinson33 Please create an fix, a corresponding unit test and I will merge in the pull request.

**Comment by GregFinzer** [comment]
@timrobinson33 Do you have an ETA on the fix?  There is another developer @MatimalND that would like a build to NuGet.

**Comment by timrobinson33** [comment]
Hi Greg, sorry I haven't really looked into this yet. I hit the problem as a side-effect of a failing test but since I fixed the test it's not affecting me directly. It's still on my to-do list but not high priority so I don't have an ETA

**Comment by gitjsdr26** [comment]
Hi,
Is this totally fixed ?
Because I cannot see the update into the master trunk.

Regards.

**Comment by GregFinzer** [comment]
Merged
