### ISSUE TITLE
Custom comparer generic type mismatch with actual field type

### ISSUE THREAD

**Issue by RedaAouad** [GregFinzer/Compare-Net-Objects#210]
Hi,

I added a custom comparer to a nullable field but provided a non-nullable generic type:

```
class MyClass
{
    DateTimeOffset? Date { get; set; } 
}

compareLogic.Config.CustomPropertyComparer<MyClass>(x => x.Date, new CustomComparer<DateTimeOffset, DateTimeOffset>((i, j) => SomeComparisonMethod(i, j)));
```

I ran into the following runtime exception:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

Stack trace:
```
   at KellermanSoftware.CompareNetObjects.TypeComparers.CustomComparer`2.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at CompareNetObjectsTest.Program.Main(String[] args) in C:\Source\CompareNetObjectsTest\CompareNetObjectsTest\Program.cs:line 19

```

Of course the problem is that I provided a `CustomComparer<DateTimeOffset, DateTimeOffset>` (non-nullable generics) to a `DateTimeOffset?` field.

However, it took me a few days to figure it out, as my compare logic is pretty complex with lots of custom comparers. The above exception was not clear and didn't help me pinpoint the problem to a specific comparer.

Is it possible to provide more info in such case? Maybe detect during the config phase that there's a type mismatch?

Here's a repro project:
[CompareNetObjectsTest.zip](https://github.com/GregFinzer/Compare-Net-Objects/files/5353869/CompareNetObjectsTest.zip)

**Comment by GregFinzer** [comment]
Closing due to no action
