### ISSUE TITLE
Invalid CollectionMatchingSpec. No such property PropA for type B

### ISSUE THREAD

**Issue by sarooghi** [GregFinzer/Compare-Net-Objects#22]
I am trying to  compare object instance c1, and  c2 here is my object tree:
`class BaseClase 
{

}
class A :BaseClase 
{
PropA
}
class B:BaseClase
{
PropB
}
class C
{
BaseClase Prop;
} 
C1 = new C(){ Prop = new A() }
C2 = new C(){ Prop = new B()}
`
StackTrace
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareInOrder(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyInfo info)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)

**Comment by GregFinzer** [comment]
sarooghi, Sorry, I am too busy to support this project.  You will need to figure out a fix yourself.

**Comment by GregFinzer** [comment]
There is no code example for the above class.  Closing the issue.
