### ISSUE TITLE
"System.Reflection.TargetParameterCountException : Parameter count mismatch." exception on complex model with list of lists + IgnoreCollectionOrder = true

### ISSUE THREAD

**Issue by Vasar007** [GregFinzer/Compare-Net-Objects#223]
Hello!

I tried to another complex case to compare object with list of lists (yeah, that's another weird model but I need such objects for my internal tests).

I created minimal gist with example [here](https://gist.github.com/Vasar007/c5a7bd4aa8c5e26961d692d079c9cae5).

Library version: 4.72.0 (with fix for #222)

Stacktrace:
```
System.Reflection.TargetParameterCountException : Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at Sample.Tests.GenericCollections.CompareObjects(GenericCollections other) in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\GenericCollections.cs:line 127
   at Sample.Tests.Tests.ShowTheErrorDictAndList() in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\Tests.cs:line 42

```

**Important moment: I set `IgnoreCollectionOrder` to `true`. `false` value works without any issues.**

So, it looks like library tries to get value of property and does not specified `index` parameter.

**Comment by Vasar007** [comment]
I also tried to use `4.63.0` version but at this time it thows another error:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Object.GetType()
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
   at Sample.Tests.GenericCollections.CompareObjects(GenericCollections other) in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\GenericCollections.cs:line 127
   at Sample.Tests.Tests.ShowTheErrorDictAndList() in C:\Users\vasily.vasilyev\source\repos\TestProject\TestProject\Tests\Veeam.CloudBackup.Tests.Common\Tests.cs:line 42
```

I think this problem has not been resolved in previous versions.

**Comment by Vasar007** [comment]
I took a look at the code. `IgnoreOrderLogic.GetMatchIndex` throws exception at the line:

```cs
var propertyValue = info.GetValue(currentObject, null);
```

However, if we pass here `currentObject` with indexer properties (such as `List` or indexed collection or custom object with own indexer property), this call will fail because parameter `index` was not specified.

I tried to use custom object with indexer and found that library supports comparing object with indexers if such objects provides `int Count` property. So, maybe you should reuse this logic for collections as well?

I was faced the same issue using array (you can find my model from gist and replace list of lists to arrat of lists). Maybe there are some other places which you can reuse this logic with indexers.

**Comment by GregFinzer** [comment]
Please fix and I will review the pull request.

**Comment by Vasar007** [comment]
Hmmm, in that case could you please provide information about classes which works with indexers? Also if there are any tests for indexers it would be easier for me to understand your library code.

I can't promise that I will fix it quickly. However, when I have free time I will do it.

**Comment by GregFinzer** [comment]
@Vasar007 There are these tests for Indexers, IList, and Ignoring the order:

CompareIndexerTests
CompareIListTests
IgnoreOrderTests
