### ISSUE TITLE
Fails to compare Interface types when ignoring order

### ISSUE THREAD

**Issue by madiganz** [GregFinzer/Compare-Net-Objects#251]
Comparing nested lists of types based on an interface seems to be broken when ignoring collection order. Say we have something like:

```csharp
public interface IData
{
    public string Name { get; set; }
}

public class Foo : IData
{
    public string Name { get; set; }
    public string Type { get; set; }
}

public class Bar : IData
{
    public string Name { get; set; }
}

public class Test
{
    public string Description { get; set; }
    public IList<IData> Data { get; set; }
}
```

When I compare two objects of type `Test` that contain `Data` with both `Foo` and `Bar` I get this error
```
System.Exception : Invalid CollectionMatchingSpec.  No such property Type for type Bar
  Stack Trace:
     at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.GetMatchIndex(ComparisonResult result, List`1 spec, Object currentObject)        
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)    
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareOutOfOrder(CompareParms parms, Boolean reverseCompare)
   at KellermanSoftware.CompareNetObjects.IgnoreOrderTypes.IgnoreOrderLogic.CompareEnumeratorIgnoreOrder(CompareParms parms, Boolean countsDifferent)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
```

**Comment by GregFinzer** [comment]
Thank you for reporting this issue.

**Comment by GregFinzer** [comment]
Thanks!

**Comment by madiganz** [comment]
Thanks for reviewing so quickly! Are you able to do a release for this? Would like to use the updated code as soon as possible.

**Comment by GregFinzer** [comment]
The earliest I can do it is Monday night.
