### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by NaveenkumarIyappan** [GregFinzer/Compare-Net-Objects#285]
CompareNETObjects 4.79.0 is used. This library is used in .NET 7.0 core project, the `CompareLogic` is registered as

```
ComparisonConfig comparisonConfig = new ComparisonConfig()
{
    MaxDifferences = 100,
    IgnoreCollectionOrder = true,
    CompareReadOnly = false,
};
builder.Services.AddTransient(x => new CompareLogic(comparisonConfig));
```

and is called from another class as
`var result = _compareLogic.Compare(actual, expected);`

The expection with message "Collection was modified; enumeration operation may not execute." is thrown while calling this method, and here is the stack trace.

```
exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at KellermanSoftware.CompareNetObjects.ComparisonConfig.PopulateHashSets()
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object expectedObject, Object actualObject)
```

**Comment by GregFinzer** [comment]
Can you create a failing unit test in .NET Core 7 please?

**Comment by NaveenkumarIyappan** [comment]
Sorry for the delayed response.  It works when a single requests is made, but intermittently this errror is thrown when there are large number of requests or while running load test using JMeter.

**Comment by GregFinzer** [comment]
No failing unit test provided.  Closing issue.
