### ISSUE TITLE
ArgumentNullException when comparing ValueTuples with IgnoreObjectTypes = True

### ISSUE THREAD

**Issue by manchas** [GregFinzer/Compare-Net-Objects#40]
Hi
I'm comparing a List<(SomeEnum a, string b)> and the following error appears if you set the Config.IgnoreObjectTypes to true. If you let that config in false (it's default) it works... 
In my particular case I need to ignore types cause I have an IEnumerable property in the class and sometimes is a list, some other times is an array... etc.

System.ArgumentNullException occurred
  HResult=0x80004003
  Message=El valor no puede ser nulo.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at KellermanSoftware.CompareNetObjects.Cache.GetFieldInfo(ComparisonConfig config, Type type)
   at KellermanSoftware.CompareNetObjects.TypeComparers.FieldComparer.GetSecondFieldInfo(CompareParms parms, FieldInfo item)
   at KellermanSoftware.CompareNetObjects.TypeComparers.FieldComparer.CompareField(CompareParms parms, FieldInfo item)
   at KellermanSoftware.CompareNetObjects.TypeComparers.FieldComparer.PerformCompareFields(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.StructComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyInfo info)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareItems(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.EnumerableComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyInfo info)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)

**Comment by GregFinzer** [comment]
Please post example code.

**Comment by manchas** [comment]
public class A
    {
        public List<(int i, string s)> L { get; } = new List<(int i, string s)>();
    }
            var a = new A();
            a.L.Add((3, "Hello"));
            a.L.Add((5, "World"));

            var aa = new A();
            aa.L.Add((3, "Hello"));
            aa.L.Add((5, "World"));

            var cl = new CompareLogic();
            cl.Config.IgnoreObjectTypes = true;
            cl.Compare(a, aa);

**Comment by manchas** [comment]
It's a C# 7 feature, so you need VS 2017.
There, you have 2 options: target framework 4.7 (was released few days ago) OR framework 4.6.1 + Nuget "System.ValueTuple"
Hope this helps.

**Comment by GregFinzer** [comment]
Thanks for the information.  It will take me a while before I can get to this one.

**Comment by rcmdh** [comment]
I think this is a general problem for structs.  Here's another example:
    class Example
    {
        struct ExampleClass
        {
            public int Property1 { get; set; }
        }

        [Test]
        public void DemoTest()
        {
            var comparer = new CompareLogic { Config = new ComparisonConfig { IgnoreObjectTypes = true } };

            var structToCompare = new ExampleClass { Property1 = 1 };
            comparer.Compare(structToCompare, structToCompare);
        }
    }

**Comment by GregFinzer** [comment]
@manchas  @rcmdh  Fixed, please retest.

**Comment by rcmdh** [comment]
No longer throwing for me in my other tests, looks good.  Thanks.

**Comment by manchas** [comment]
Works!!! 
Thanks a lot, great work.
