### ISSUE TITLE
Enumeration has either not started or has already finished

### ISSUE THREAD

**Issue by jcd79** [GregFinzer/Compare-Net-Objects#44]
Hi! 
IgnoreCollectionOrder = true

I compare 2 objects of same type. (foo and bar)
Each object contains a list of another objects (foo.list, bar.list)
In this case both foo.list and bar.list contains 1 object - this object has changed and I cannot find difference with IgnoreCollectionOrder = false, so I'm trying with true.

Then following exception is thrown:

`{"error":{"message":"Enumeration has either not started or has already finished.","type":"Internal server error","code":500,"stacktrace":"   
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.List1.Enumerator.System.Collections.IEnumerator.get_Current()
at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.ChildIsListOrDictionary(CompareParms parms) 
at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)   
at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms)
at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)
........"}}`

Any hint?

Edit: To be more precise with what I want to achive.
The comparer does not find any changes on the properties in foo.list and bar.list when there is 1 object in both of them. I was hoping that "IgnoreCollectionOrder" would force a comparison of the 2 objects in the list. That's all I want. I'm not sure, in this case, why it does not compare child properties by default. It seems like a reasonable thing to do :)

/Jacob

**Comment by GregFinzer** [comment]
Please post an example failing test.

**Comment by jcd79** [comment]
Weird! Creating a code sample so that you could run it. So far it always finds the difference. But when I debug the actual running example with bug it never detects the difference. Even though I can clearly see the difference when inspecting the objects at runtime :/

Give me some more time - either I will make the problem reproducible or in the process fix the problem. 50/50 chance both ways - as of now ;)

**Comment by jcd79** [comment]
My bad...
I did not understand clearly that the MembersToInclude list also limited properties on child objects.
I swapped it around to use MembersToIgnore.
