### ISSUE TITLE
Installing the NuGet package to a Windows Phone 8.1 project does not add a reference

### ISSUE THREAD

**Issue by viswanathr88** [GregFinzer/Compare-Net-Objects#69]
I just created a new Windows Phone 8.1 Unit Test project (Not Silverlight, the RT version) project using Microsoft Visual Studio 2015 and I added CompareNETObjects to the project. The nugget package installs successfully but no reference is added by visual studio.

When I try to refer the portable library manually, the code builds but tests fail with the following error:
System.InvalidOperationException: The API 'System.Array.get_SyncRoot()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.

Test Name:	AuthorParseTest
Test FullName:	<App-Name>.Xml.Tests.ParseTests.AuthorParseTest
Test Source:	C:\Users\<user-name>\source\repos\<App-Name>\Test\<App-Name>.Xml.Tests\ParseTests.cs : line 31
Test Outcome:	Failed
Test Duration:	0:00:00.010988

Result StackTrace:	
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.HandleNormalProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.GetCurrentProperties(CompareParms parms, Object objectValue, Type objectType)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareProperties(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ListComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.CompareProperty(CompareParms parms, PropertyEntity info, List`1 object2Properties)
   at KellermanSoftware.CompareNetObjects.TypeComparers.PropertyComparer.PerformCompareProperties(CompareParms parms, Boolean ignoreBaseList)
   at KellermanSoftware.CompareNetObjects.TypeComparers.ClassComparer.CompareType(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.RootComparer.Compare(CompareParms parms)
   at KellermanSoftware.CompareNetObjects.CompareLogic.Compare(Object object1, Object object2)
   at <App-Name>.Xml.Tests.ParseTests.<AuthorParseTest>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	Test method <App-Name>.Xml.Tests.ParseTests.AuthorParseTest threw exception: 
System.InvalidOperationException: The API 'System.Array.get_SyncRoot()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.

**Comment by GregFinzer** [comment]
Can you give your example code?

**Comment by GregFinzer** [comment]
Windows Phone has less than a tenth of a percent of the market share.  Not worth supporting.  Sorry, I was once a Windows Phone user too.  It is too bad, it was a wonderful platform.
